# Generated by Django 6.0.3 on 2026-08-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0002_alter_question_passage_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_selections',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
