# Generated by Django 6.0.3 on 2026-08-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0003_question_max_selections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_types',
            field=models.CharField(choices=[('text-completion', 'Text Completion'), ('text-completion-double', 'Text Completion Double'), ('text-completion-triple', 'Text Completion Triple'), ('sentence-equivalence', 'Sentence Equivalence'), ('reading-single', 'Reading Single'), ('reading-multiple', 'Reading Multiple')], max_length=50),
        ),
    ]
