# Generated by Django 6.0.3 on 2026-08-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0004_alter_question_question_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_types',
            new_name='question_type',
        ),
    ]
