# Generated by Django 6.0.3 on 2026-08-30 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0005_rename_question_types_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='passage_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_questions', to='gradsprint.question'),
        ),
    ]
