# Generated by Django 6.0.3 on 2026-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0006_alter_question_passage_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
