# Generated by Django 6.0.3 on 2026-09-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0007_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quantityA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='quantityB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('quantative-comparison', 'Quantative Comparison'), ('quant-single', 'Quant Single'), ('quant-multiple', 'Quant Multiple'), ('numeric-entry', 'Numeric Entry'), ('data-interpretation-single', 'Data Interpretation Single'), ('text-completion', 'Text Completion'), ('sentence-equivalence', 'Sentence Equivalence'), ('reading-single', 'Reading Single'), ('reading-multiple', 'Reading Multiple')], max_length=50),
        ),
    ]
