# Generated by Django 6.0.3 on 2026-09-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0009_rename_quantitya_question_quantity_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quantity_a',
            new_name='quantityA',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quantity_b',
            new_name='quantityB',
        ),
    ]
