# Generated by Django 6.0.3 on 2026-09-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0010_rename_quantity_a_question_quantitya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('quantitative-comparison', 'Quantitative Comparison'), ('quant-single', 'Quant Single'), ('quant-multiple', 'Quant Multiple'), ('numeric-entry', 'Numeric Entry'), ('data-interpretation-single', 'Data Interpretation Single'), ('text-completion', 'Text Completion'), ('sentence-equivalence', 'Sentence Equivalence'), ('reading-single', 'Reading Single'), ('reading-multiple', 'Reading Multiple')], max_length=50),
        ),
    ]
