# Generated by Django 6.0.3 on 2026-09-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0011_alter_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quantityA',
            new_name='quantity_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quantityB',
            new_name='quantity_b',
        ),
    ]
