# Generated by Django 6.0.3 on 2026-09-05 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0014_alter_question_subtopic_alter_question_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blank',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='blankchoice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='max_selections',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NumericValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_value', to='gradsprint.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.JSONField(blank=True, default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='gradsprint.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbal_score', models.PositiveIntegerField(default=130)),
                ('quant_score', models.PositiveIntegerField(default=130)),
                ('total_score', models.PositiveIntegerField(default=260)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_attempted_question', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='gradsprint.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
