# Generated by Django 6.0.3 on 2026-09-11 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0015_alter_blank_options_alter_blankchoice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankchoice',
            name='blank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankchoices', to='gradsprint.blank'),
        ),
    ]
