# Generated by Django 6.0.3 on 2026-09-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradsprint', '0017_alter_blankchoice_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericvalue',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='numeric_value', to='gradsprint.question'),
        ),
    ]
