# Generated by Django 6.0.3 on 2026-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trx_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED')], default='PENDING', max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
