# Generated by Django 6.0.3 on 2026-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
